import Navbar from '@/components/Navbar';
import '@/styles/globals.css';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Ultra Mega Shopping App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
